export default {
  toMain: 'To home',
  dashboard: 'Dashboard',
  spendingList: 'Spending list',
  categories: 'Categories',
  category: 'Category',
  report: 'Report',
  categoryCreate: 'Category create',
  categoryEdit: 'Category edit',
  currentInvoice: 'Current invoice',
  currencyCourse: 'Currency course',
  currency: 'Currency',
  course: 'Course',
  date: 'Date',
  amount: 'Amount',
  type: 'Type',
  open: 'Open',
  income: 'Income',
  outcome: 'Outcome',
  createPost: 'Create post',
  limit: 'Limit',
  totalSpent: 'Total spent',
  of: 'Of',
  site: 'Site',
  settings: 'Settings',
  exit: 'Exit',
  profile: 'Profile',
  uploadAvatar: 'Upload avatar',
  maxSize: 'Max size',
  removeAvatar: 'Remove avatar',
  spendingEmpty: 'Spending empty',
  categoriesEmpty: 'Categories empty',
  spendingCreate: 'Spending list create',
  selectType: 'Select type',
  description: 'Description',
  spendingListView: 'Spending list view',
  noDescription: 'No description',
}