export const
  
    /**
     * MESSAGES
     */
    SET_TOASTED_MESSAGE = 'SET_TOASTED_MESSAGE',
    CLEAR_TOASTED_MESSAGE = 'CLEAR_TOASTED_MESSAGE',
  
    /**
     * AUTH
     */
    SET_IS_AUTH = 'SET_IS_AUTH',
  
    /**
     * LANG
     */
    SET_LANG = 'SET_LANG',
    
    /**
     * CURRENCY
     */
    SET_CURRENCY = 'SET_CURRENCY',
    CURRENCY_LOADER = 'CURRENCY_LOADER',
  
    /**
     * SPENDING
     */
    SET_SPENDING = 'SET_SPENDING',
    SET_SPENDING_SINGLE = 'SET_SPENDING_SINGLE',
    SPENDING_LOADING = 'SPENDING_LOADING',
    CLEAR_SPENDING = 'CLEAR_SPENDING',
  
    /**
     * CATEGORIES
     */
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_CATEGORY_SINGLE = 'SET_CATEGORY_SINGLE',
    CATEGORIES_LOADING = 'CATEGORIES_LOADING',
    CLEAR_CATEGORIES = 'CLEAR_CATEGORIES',
  
    /**
     * USER
     */
    SET_USER = 'SET_USER',
    USER_LOADING = 'USER_LOADING',
    CLEAR_USER = 'CLEAR_USER';
    

  