export default {
  home: 'Главная',
  toMain: 'На главную',
  dashboard: 'Админ панель',
  spendingList: 'Список расходов',
  categories: 'Категории',
  category: 'Категория',
  report: 'Отчет',
  categoryCreate: 'Создание категории',
  categoryEdit: 'Редактирование категории',
  currentInvoice: 'Текущий счет',
  currencyCourse: 'Курс валюты',
  currency: 'Валюта',
  course: 'Курс',
  date: 'Дата',
  amount: 'Сумма',
  type: 'Тип',
  open: 'Открыть',
  income: 'Доход',
  outcome: 'Расход',
  createPost: 'Создать запись',
  limit: 'Лимит',
  totalSpent: 'Всего потрачено',
  of: 'Из',
  site: 'Сайт',
  settings: 'Настройки',
  exit: 'Выход',
  profile: 'Профиль',
  uploadAvatar: 'Загрузить аватар',
  maxSize: 'Максимальный размер',
  removeAvatar: 'Удалить аватар',
  spendingEmpty: 'Записей трат нет',
  categoriesEmpty: 'Категорий нет',
  spendingCreate: 'Создание записи',
  selectType: 'Выберете тип',
  description: 'Описание',
  spendingListView: 'Просмотр записи',
  noDescription: 'Нет описания',
}