export default {
  modal: 'Окно',
  login: 'Авторизация',
  registration: 'Регистрация',
  passwordRecovery: 'Восстановление пароля',
  sendResetPassword: 'Отправить сообщение для сброса пароля на вашу почту?',
  back: 'Назад',
  resetThePassword: 'Сбросить пароль',
  cancel: 'Закрыть',
  confirm: 'OK',
  singIn: 'Войти',
  singUp: 'Регистрация',
  noAccount: 'Нет аккаунта?',
  forgotPassword: 'Забыли пароль?',
  haveAnAccount: 'Есть аккаунт?',
}